# Generated by Django 4.1 on 2022-12-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0002_alter_myuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_superuser',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Super user'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
