# Generated by Django 4.1 on 2022-12-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0004_myuser_groups_myuser_total_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='total_score',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
    ]
