# Generated by Django 4.1 on 2022-12-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0005_alter_myuser_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultanswersmodel',
            name='question_name',
            field=models.CharField(max_length=255, verbose_name='Questions'),
        ),
    ]
