# Generated by Django 4.1 on 2022-12-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0006_alter_resultanswersmodel_question_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultAnswersModel',
        ),
    ]
