# Generated by Django 4.1 on 2022-12-16 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0007_delete_resultanswersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAnswersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=255, verbose_name='Questions')),
                ('answer_name', models.CharField(max_length=100)),
                ('weight_number', models.DecimalField(decimal_places=4, max_digits=9)),
                ('weight_type', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
