# Generated by Django 4.1 on 2022-12-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0008_resultanswersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='total_score',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=9),
        ),
    ]
