# Generated by Django 4.0.4 on 2022-07-06 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['user'], 'verbose_name_plural': 'User Data'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='head_image',
            field=models.ImageField(default='head_images/default.png', upload_to='head_images'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
